// Curriculum data. Each card: n name, h hex, c code (optional), s story {hist,cult,mind}, k hook {w work, a artist, y year, u url, note}, t trivia clue
const W = "https://en.wikipedia.org/wiki/";
const LEVELS = [
{ id:"basic", lv:1, title:"Foundations", school:"Basic color terms", blurb:"The eleven basic color words. Linguists Berlin and Kay (1969) found languages tend to add them in a similar order: black and white, then red, then green and yellow, then blue.",
 cards:[
 {n:"Red",h:"#D62F2F",t:"After black and white, the first color word most languages gain",
  s:{hist:"Red ochre is one of humanity's oldest pigments. A paint-making kit about 100,000 years old was found in Blombos Cave, South Africa.",cult:"Luck and weddings in China; danger and stop signals almost everywhere.",mind:"Red raises arousal and grabs attention. Studies claiming red makes you win or lose are mixed and often fail to replicate."},
  k:{w:"The Red Studio",a:"Henri Matisse",y:"1911",u:W+"The_Red_Studio",note:"Matisse flooded the whole room with one red, so walls, floor and furniture dissolve into it."}},
 {n:"Orange",h:"#F07A1A",t:"English named this color after a fruit; before that it was called yellow-red",
  s:{hist:"The word arrived with the fruit. Before the 1500s English speakers said geoluread, yellow-red.",cult:"The Dutch House of Orange, Buddhist robes, and high-visibility safety gear.",mind:"Reads as warm, loud and friendly. It is a favorite for things that must be noticed fast."},
  k:{w:"The Scream",a:"Edvard Munch",y:"1893",u:W+"The_Scream",note:"The swirling blood-orange sky is the emotional engine of the picture."}},
 {n:"Yellow",h:"#F2C81F",t:"Goethe called it the color nearest to light",
  s:{hist:"Yellow ochre appears in the Lascaux cave paintings. Egyptians also used orpiment, a toxic arsenic yellow.",cult:"Imperial yellow was reserved for the emperor in Qing China.",mind:"In his Theory of Colours (1810) Goethe called yellow the color closest to light, cheerful and warming."},
  k:{w:"The Yellow House",a:"Vincent van Gogh",y:"1888",u:W+"The_Yellow_House_(painting)",note:"Van Gogh painted his Arles home in the color he linked with hope and sunlight."}},
 {n:"Green",h:"#2E9A4F",t:"A popular 1800s version was full of arsenic and hung on bedroom walls",
  s:{hist:"Scheele's green (1775) and emerald green were made with arsenic and used in wallpaper, dresses and toys.",cult:"A sacred color in Islam, the color of Ireland, and the universal go signal.",mind:"Goethe recommended green for rooms you live in, saying the eye rests on it."},
  k:{w:"The Arnolfini Portrait",a:"Jan van Eyck",y:"1434",u:W+"Arnolfini_Portrait",note:"The bride's deep green gown, with its heavy folds, dominates the room."}},
 {n:"Blue",h:"#2563C9",t:"Homer never used a word for it, calling the sea wine-dark instead",
  s:{hist:"Egyptian blue, made more than 4,000 years ago, is the first known synthetic pigment. William Gladstone noticed Homer never calls the sea blue.",cult:"Medieval painters saved expensive ultramarine for the Virgin Mary's robe.",mind:"In surveys across many countries, blue is the most common favorite color."},
  k:{w:"The Old Guitarist",a:"Pablo Picasso",y:"1903",u:W+"The_Old_Guitarist",note:"A key work of Picasso's Blue Period, painted while he was grieving a friend."}},
 {n:"Purple",h:"#7B3FA0",t:"An 18-year-old chemist made it cheap by accident in 1856",
  s:{hist:"Ancient Tyrian purple came from sea snails. In 1856 William Perkin, aged 18, accidentally made mauveine, the first synthetic dye.",cult:"Royalty in Rome and Byzantium; later the suffragettes' purple, white and green.",mind:"Often read as rare, spiritual or ambiguous, because for millennia almost nobody could afford it."}},
 {n:"Pink",h:"#F28DB2",t:"A 1918 trade magazine recommended it for boys",
  s:{hist:"The word comes from the flower pinks (Dianthus), whose frilled petals look cut with pinking shears. Sevres porcelain made Pompadour pink fashionable in the 1750s.",cult:"Pink for girls is recent marketing. In 1918 a US trade magazine advised pink for boys; the girl-pink rule hardened through mid-1900s retail. Millennial pink returned in the 2010s.",mind:"Baker-Miller pink was painted in jail cells in 1979 to calm inmates. Later studies did not confirm the effect."},
  k:{w:"The Swing",a:"Jean-Honore Fragonard",y:"1767",u:W+"The_Swing_(Fragonard)",note:"The frothy pink dress is the centre of this Rococo flirtation."}},
 {n:"Brown",h:"#7A5230",t:"One version was ground from Egyptian mummies",
  s:{hist:"Earth browns like umber and sienna are among the oldest pigments. Mummy brown was really made from ground mummies into the 1900s.",cult:"Franciscan monks wore undyed brown as a sign of humility.",mind:"Reads as earthy, solid and dependable, and rarely as exciting."}},
 {n:"Grey",h:"#8C9096",t:"Whistler named his mother's portrait after it",
  s:{hist:"Grisaille, painting entirely in greys, was used for altarpiece wings and study sketches.",cult:"Grey suits, grey areas, grey matter: the color of neutrality and thought.",mind:"Grey lets other colors speak. Painters use it to make a small amount of color glow."},
  k:{w:"Whistler's Mother",a:"James McNeill Whistler",y:"1871",u:W+"Whistler%27s_Mother",note:"Its real title is Arrangement in Grey and Black No. 1."}},
 {n:"Black",h:"#16171A",t:"Chanel made it chic in 1926",
  s:{hist:"Charcoal and soot blacks fill the Chauvet cave paintings. Vantablack (2014) absorbs about 99.96% of light.",cult:"Mourning in the West; elegance after Chanel's little black dress in 1926.",mind:"Physically, black is the absence of light. Malevich called his Black Square the zero of form."},
  k:{w:"Black Square",a:"Kazimir Malevich",y:"1915",u:W+"Black_Square_(painting)",note:"Hung in the corner like an icon at its first show in Petrograd."}},
 {n:"White",h:"#F7F6F2",t:"Newton's prism showed it contains every other color",
  s:{hist:"In the 1660s Isaac Newton split white sunlight with a prism and showed it contains the whole spectrum.",cult:"Purity and weddings in the West; mourning in much of East Asia.",mind:"White can mean emptiness or totality, depending on whether you think in paint or in light."},
  k:{w:"Suprematist Composition: White on White",a:"Kazimir Malevich",y:"1918",u:W+"Suprematist_Composition:_White_on_White",note:"A white square tilted on a white ground, about as far as painting can strip down."}}
 ]},
{ id:"nuance", lv:2, title:"Nuances", school:"Shades and neighbors", blurb:"The names between the basics. Each lesson is one family of close neighbors, so you learn to tell scarlet from carmine and sage from moss. Screen values are approximate.",
 cards:[
 {n:"Scarlet",h:"#FF2400",g:"Reds",t:"A bright red that leans toward orange, the red of British army coats"},
 {n:"Cardinal",h:"#C41E3A",g:"Reds",t:"Named for the robes of Catholic cardinals: a strong red that leans slightly cool"},
 {n:"Carmine",h:"#960018",g:"Reds",t:"A deep red first made from cochineal insects, leaning toward blue"},
 {n:"Burgundy",h:"#800020",g:"Reds",t:"Named after the wine of Burgundy, France: a dark red with a purple cast"},
 {n:"Oxblood",h:"#4A0000",g:"Reds",t:"The darkest red, close to brown, and a classic color for leather shoes"},
 {n:"Saffron",h:"#F4C430",g:"Earth oranges",t:"The yellow-orange of the costly spice, which comes from crocus flowers"},
 {n:"Amber",h:"#FFBF00",g:"Earth oranges",t:"The golden orange-yellow of fossilized tree resin, and of the middle traffic light"},
 {n:"Ochre",h:"#CC7722",g:"Earth oranges",t:"A yellow-brown earth pigment, used since prehistoric cave paintings"},
 {n:"Terracotta",h:"#E2725B",g:"Earth oranges",t:"Italian for baked earth: the orange-brown of clay pots and roof tiles"},
 {n:"Rust",h:"#B7410E",g:"Earth oranges",t:"The color of iron oxide, a darker and browner orange than terracotta"},
 {n:"Ivory",h:"#FFFFF0",g:"Whites",t:"An off-white with a faint yellow, like elephant tusk"},
 {n:"Cream",h:"#FFFDD0",g:"Whites",t:"Warmer and yellower than ivory, like dairy cream"},
 {n:"Champagne",h:"#F7E7CE",g:"Whites",t:"A pale golden beige, like the wine"},
 {n:"Beige",h:"#F5F5DC",g:"Whites",t:"From the French word for natural, undyed wool: a pale sandy tone"},
 {n:"Ecru",h:"#C2B280",g:"Whites",t:"French for raw: the greyish beige of unbleached linen"},
 {n:"Celadon",h:"#ACE1AF",g:"Greens",t:"The pale grey-green of Chinese and Korean glazed ceramics"},
 {n:"Sage",h:"#B2AC88",g:"Greens",t:"The soft grey-green of the herb's leaves"},
 {n:"Moss",h:"#8A9A5B",g:"Greens",t:"Darker and yellower than sage, like moss on stone"},
 {n:"Emerald",h:"#50C878",g:"Greens",t:"A bright gem green, lighter than jade"},
 {n:"Jade",h:"#00A86B",g:"Greens",t:"A cool green that leans toward blue, named after the gemstone"},
 {n:"Powder Blue",h:"#B0E0E6",g:"Blues",t:"A very pale blue with a hint of green-grey"},
 {n:"Periwinkle",h:"#CCCCFF",g:"Blues",t:"A pale blue that leans toward lavender, named after the flower"},
 {n:"Cornflower",h:"#6495ED",g:"Blues",t:"The mid blue of the wildflower, softer than azure"},
 {n:"Azure",h:"#007FFF",g:"Blues",t:"The bright blue of a clear sky; in heraldry, the word for any blue"},
 {n:"Sapphire",h:"#0F52BA",g:"Blues",t:"A deep, rich gem blue, darker than azure"},
 {n:"Lilac",h:"#C8A2C8",g:"Purples",t:"The pale pinkish purple of lilac blossoms"},
 {n:"Heliotrope",h:"#DF73FF",g:"Purples",t:"A bright pink-purple named after a flower that turns toward the sun"},
 {n:"Amethyst",h:"#9966CC",g:"Purples",t:"The medium purple of the quartz gemstone"},
 {n:"Violet",h:"#8F00FF",g:"Purples",t:"The purple at the end of the rainbow, bluer than purple"},
 {n:"Aubergine",h:"#3D0734",g:"Purples",t:"The very dark purple of eggplant skin; aubergine is the British word for eggplant"},
 {n:"Ash",h:"#B2BEB5",g:"Greys",t:"A light grey with a faint green, like wood ash"},
 {n:"Pewter",h:"#899499",g:"Greys",t:"The soft medium grey of the tin alloy"},
 {n:"Taupe",h:"#483C32",g:"Greys",t:"French for mole: a grey-brown, darker than most people picture"},
 {n:"Gunmetal",h:"#2A3439",g:"Greys",t:"The dark blue-grey of tarnished gun bronze"},
 {n:"Charcoal",h:"#36454F",g:"Greys",t:"A dark grey with a hint of blue, like burned wood"}
 ]},
{ id:"web", lv:2, title:"Everyday names", school:"Web colors (CSS / X11)", blurb:"The named colors every browser knows. Designers type these into code every day, so knowing them is a practical superpower.",
 cards:[
 {n:"Tomato",h:"#FF6347"},{n:"Coral",h:"#FF7F50"},{n:"Salmon",h:"#FA8072"},
 {n:"Crimson",h:"#DC143C",t:"Its name comes from an insect, the same root as carmine",s:{hist:"From Arabic qirmiz, the kermes insect crushed to make red dye.",cult:"Cardinals, academic gowns and many university colors.",mind:"Deeper and more serious than pure red."}},
 {n:"Maroon",h:"#800000",s:{hist:"From French marron, chestnut."}},
 {n:"Gold",h:"#FFD700"},{n:"Khaki",h:"#F0E68C",t:"Hindi-Urdu for dusty, worn by British troops in India",s:{hist:"From Hindi-Urdu khaki, dusty. British regiments in India dyed uniforms this color in the 1840s for camouflage.",cult:"Now the color of chinos and safari clothes."}},
 {n:"Goldenrod",h:"#DAA520"},{n:"Olive",h:"#808000"},
 {n:"Chartreuse",h:"#7FFF00",t:"Named after a liqueur made by monks",s:{hist:"Named after the green liqueur made by Carthusian monks at the Grande Chartreuse monastery since the 1700s."}},
 {n:"ForestGreen",h:"#228B22"},{n:"SeaGreen",h:"#2E8B57"},
 {n:"Teal",h:"#008080",t:"Named after the stripe on a duck's head",s:{hist:"Named after the Eurasian teal, a duck with a blue-green stripe around its eye."}},
 {n:"Turquoise",h:"#40E0D0",t:"Literally means Turkish",s:{hist:"The stone reached Europe through Turkey, so the French called it turquoise, Turkish."}},
 {n:"Aquamarine",h:"#7FFFD4"},{n:"SteelBlue",h:"#4682B4"},{n:"RoyalBlue",h:"#4169E1"},
 {n:"Navy",h:"#000080",s:{hist:"Royal Navy officers got dark blue uniforms in 1748, and the name stuck."}},
 {n:"Indigo",h:"#4B0082",t:"Newton added it to the rainbow so there would be seven colors, like musical notes",s:{hist:"Indigo dye comes from India; the Greek indikon means from India.",cult:"Blue jeans are traditionally indigo-dyed.",mind:"Newton added indigo to the spectrum so it would have seven colors, matching the seven notes of a musical scale. Many people cannot pick it out at all."}},
 {n:"Orchid",h:"#DA70D6"},{n:"Plum",h:"#DDA0DD"},{n:"Lavender",h:"#E6E6FA"},
 {n:"Fuchsia",h:"#FF00FF",s:{hist:"Named after the fuchsia flower, which honors the German botanist Leonhart Fuchs."}},
 {n:"HotPink",h:"#FF69B4"},
 {n:"RebeccaPurple",h:"#663399",t:"Added to web standards in 2014 in memory of a six-year-old girl",s:{hist:"Added to CSS in 2014 in memory of Rebecca Meyer, daughter of web pioneer Eric Meyer, who died at age six. Purple was her favorite color.",mind:"A rare case of a technical standard carrying a personal story."}},
 {n:"Chocolate",h:"#D2691E"},{n:"Sienna",h:"#A0522D"},{n:"Tan",h:"#D2B48C"},{n:"Wheat",h:"#F5DEB3"},{n:"SlateGray",h:"#708090"}
 ]},
{ id:"crayola", lv:3, title:"Playful names", school:"Crayola", blurb:"Crayon names are a mirror of culture. Flesh became Peach in 1962 during the civil rights era, Prussian Blue became Midnight Blue in 1958, and in 1993 the public named new colors like Macaroni and Cheese. Screen values are approximate.",
 cards:[
 {n:"Peach",h:"#FFCBA4",t:"Renamed from Flesh in 1962",s:{hist:"Crayola renamed Flesh to Peach in 1962, recognizing that skin comes in many colors.",cult:"In 2020 Crayola released Colors of the World, 24 crayons for skin tones."}},
 {n:"Midnight Blue",h:"#1A4876",t:"Renamed in 1958 because teachers said kids did not know this history",s:{hist:"Originally Prussian Blue. Crayola renamed it in 1958 after teachers said children no longer knew Prussian history."}},
 {n:"Chestnut",h:"#BC5D58",s:{hist:"Renamed from Indian Red in 1999, partly to avoid confusion about Native Americans; the name actually referred to a pigment from India."}},
 {n:"Macaroni and Cheese",h:"#FFBD88",t:"Named by the public in 1993"},
 {n:"Granny Smith Apple",h:"#A8E4A0"},{n:"Purple Mountains' Majesty",h:"#9D81BA"},
 {n:"Robin's Egg Blue",h:"#1FCECB",s:{hist:"Robins make this blue with biliverdin, a pigment related to bile, deposited in the eggshell."}},
 {n:"Razzmatazz",h:"#E3256B"},{n:"Mango Tango",h:"#FF8243"},{n:"Inchworm",h:"#B2EC5D"},
 {n:"Wild Blue Yonder",h:"#A2ADD0"},{n:"Timberwolf",h:"#DBD7D2"},{n:"Outer Space",h:"#414A4C"},
 {n:"Atomic Tangerine",h:"#FF9966"},{n:"Cerulean",h:"#1DACD6",s:{hist:"From Latin caeruleum, the sky blue of the heavens."}},
 {n:"Dandelion",h:"#FDDB6D",s:{hist:"Retired in 2017 and replaced by Bluetang, a blue."}},
 {n:"Jazzberry Jam",h:"#CA3767"},{n:"Laser Lemon",h:"#FEFE22"},{n:"Screamin' Green",h:"#76FF7A"},
 {n:"Shocking Pink",h:"#FB7EFD"},{n:"Tickle Me Pink",h:"#FC89AC"},
 {n:"Burnt Sienna",h:"#EA7E5D",s:{hist:"Raw sienna earth from Siena, Italy, roasted until it turns red-brown."}},
 {n:"Fuzzy Wuzzy",h:"#CC6666"},{n:"Unmellow Yellow",h:"#FFFF66"},{n:"Manatee",h:"#979AAA"},{n:"Denim",h:"#2B6CC4"},{n:"Blizzard Blue",h:"#ACE5EE"}
 ]},
{ id:"art", lv:4, title:"Pigments & masterpieces", school:"Artist pigments", blurb:"Real pigments with real stories: poisons, accidents, fortunes and the paintings that made them famous. Screen values are approximate.",
 cards:[
 {n:"Ultramarine",h:"#1F3FA8",t:"Ground from a stone mined in Afghanistan; once pricier than gold",
  s:{hist:"Made from lapis lazuli mined in Afghanistan. The name means beyond the sea. In 1826 France offered a prize for a synthetic version, won by Jean-Baptiste Guimet.",cult:"Reserved for the Virgin Mary's robe because of its cost.",mind:"Its price turned it into a symbol of the sacred."},
  k:{w:"Girl with a Pearl Earring",a:"Johannes Vermeer",y:"c. 1665",u:W+"Girl_with_a_Pearl_Earring",note:"The blue of the turban is natural ultramarine."}},
 {n:"Prussian Blue",h:"#003153",t:"Made by accident in Berlin around 1706",
  s:{hist:"Made by accident in Berlin around 1706, the first modern synthetic pigment. Later it gave blueprints their color.",cult:"Imported into Japan, it transformed woodblock prints.",mind:"It is also a medicine: an antidote for thallium and radioactive cesium poisoning."},
  k:{w:"The Great Wave off Kanagawa",a:"Katsushika Hokusai",y:"c. 1831",u:W+"The_Great_Wave_off_Kanagawa",note:"One of the first great Japanese prints to use imported Prussian blue."}},
 {n:"Cobalt Blue",h:"#0047AB",
  s:{hist:"Louis Jacques Thenard made the modern pigment in 1802. Cobalt ores had long colored Chinese blue-and-white porcelain."},
  k:{w:"The Starry Night",a:"Vincent van Gogh",y:"1889",u:W+"The_Starry_Night",note:"Van Gogh used cobalt blue alongside ultramarine in the swirling sky."}},
 {n:"International Klein Blue",h:"#002FA7",t:"An artist patented a way to keep it matte",
  s:{hist:"Yves Klein developed a binder with chemists that kept ultramarine pigment matte and intense, and filed for a patent in 1960.",mind:"Klein said blue has no dimension; it is beyond dimension."},
  k:{w:"IKB 191",a:"Yves Klein",y:"1962",u:W+"International_Klein_Blue",note:"A canvas of nothing but this blue."}},
 {n:"Vermilion",h:"#E34234",
  s:{hist:"Made from cinnabar, a mercury ore, and later synthesized. It colors Chinese lacquer.",cult:"Romans painted the faces of triumphant generals red.",mind:"For centuries the brightest red available, and poisonous to make."},
  k:{w:"Assumption of the Virgin",a:"Titian",y:"1516-18",u:W+"Assumption_of_the_Virgin_(Titian)",note:"Follow the reds of the robes up the composition."}},
 {n:"Sanguine",h:"#9E3B2C",s:{hist:"Red chalk, an iron-rich earth. Its name means blood-colored. Renaissance artists loved it for drawing flesh."},
  k:{w:"Portrait of a Man in Red Chalk",a:"Leonardo da Vinci",y:"c. 1512",u:W+"Portrait_of_a_Man_in_Red_Chalk",note:"Widely believed to be Leonardo's self-portrait."}},
 {n:"Lead-Tin Yellow",h:"#E7C24E",t:"Forgotten for 200 years and rediscovered in the 1940s",
  s:{hist:"Used heavily until about 1750, then forgotten. Scientists rediscovered it in the 1940s while analyzing old paintings."},
  k:{w:"The Milkmaid",a:"Johannes Vermeer",y:"c. 1658",u:W+"The_Milkmaid_(Vermeer)",note:"Her bodice glows with lead-tin yellow."}},
 {n:"Chrome Yellow",h:"#FFA700",
  s:{hist:"From chromium, discovered in 1797. It reached painters in the 1810s and tends to darken over time."},
  k:{w:"Sunflowers",a:"Vincent van Gogh",y:"1888",u:W+"Sunflowers_(Van_Gogh_series)",note:"Van Gogh built the petals from the then-new chrome yellow."}},
 {n:"Scheele's Green",h:"#4F8A3B",t:"Arsenic wallpaper blamed in rumors about Napoleon's death",
  s:{hist:"Invented by Carl Wilhelm Scheele in 1775 using arsenic. Damp walls released toxic fumes.",cult:"Rumors linked Napoleon's death to the green wallpaper on Saint Helena."}},
 {n:"Verdigris",h:"#43B3AE",s:{hist:"Made by exposing copper to vinegar fumes and scraping off the green crust. Unstable, it often browns in old paintings.",cult:"Copper roofs and statues weather to a similar green patina."}},
 {n:"Tyrian Purple",h:"#66023C",t:"Thousands of sea snails for a single gram",
  s:{hist:"Extracted from murex sea snails, thousands for each gram of dye.",cult:"Byzantine heirs were porphyrogennetos, born in the purple."},
  k:{w:"Mosaic of Justinian, San Vitale",a:"Byzantine workshop",y:"c. 547",u:W+"Basilica_of_San_Vitale",note:"Only the emperor wears the purple robe."}},
 {n:"Mauve",h:"#8E4585",s:{hist:"William Perkin's mauveine (1856) launched the synthetic dye industry.",cult:"The 1890s were called the Mauve Decade."}},
 {n:"Raw Umber",h:"#826644",s:{hist:"An earth pigment. The name comes either from Umbria or from terra d'ombra, earth of shadow."},
  k:{w:"The Night Watch",a:"Rembrandt",y:"1642",u:W+"The_Night_Watch",note:"Rembrandt built his famous darkness from earth browns."}},
 {n:"Mummy Brown",h:"#8F4B28",t:"Painters stopped using it once they learned what it was made of",
  s:{hist:"Made from ground Egyptian mummies until supplies ran out in the 1900s. Pre-Raphaelite painter Edward Burne-Jones reportedly buried his tube on learning the truth."}},
 {n:"Lead White",h:"#F2EEE4",s:{hist:"The main white of European painting for centuries, and toxic.",cult:"Venetian ceruse, a lead-based face makeup, was fashionable for centuries despite the poison."},
  k:{w:"Symphony in White, No. 1",a:"James McNeill Whistler",y:"1862",u:W+"Symphony_in_White,_No._1:_The_White_Girl",note:"Whites on whites, built with lead white."}},
 {n:"Payne's Grey",h:"#536878",s:{hist:"Mixed by the English watercolorist William Payne in the late 1700s for stormy skies and shadows."}}
 ]},
{ id:"pantone", lv:5, title:"Design industry", school:"Pantone Color of the Year", blurb:"Lawrence Herbert's Pantone Matching System (1963) gave printers a shared numbered language. Since 2000 Pantone names a Color of the Year. Codes are real; screen hex values are approximate.",
 cards:[
 {n:"Cerulean",c:"15-4020",y:2000,h:"#9BB7D4",t:"The first Color of the Year"},
 {n:"Blue Turquoise",c:"15-5217",y:2005,h:"#53B0AE"},{n:"Blue Iris",c:"18-3943",y:2008,h:"#5A5B9F"},
 {n:"Mimosa",c:"14-0848",y:2009,h:"#F0C05A"},{n:"Turquoise",c:"15-5519",y:2010,h:"#45B5AA"},
 {n:"Honeysuckle",c:"18-2120",y:2011,h:"#D94F70"},{n:"Tangerine Tango",c:"17-1463",y:2012,h:"#DD4124"},
 {n:"Emerald",c:"17-5641",y:2013,h:"#009473"},{n:"Radiant Orchid",c:"18-3224",y:2014,h:"#B163A3"},
 {n:"Marsala",c:"18-1438",y:2015,h:"#955251"},{n:"Greenery",c:"15-0343",y:2017,h:"#88B04B"},
 {n:"Ultra Violet",c:"18-3838",y:2018,h:"#5F4B8B"},{n:"Living Coral",c:"16-1546",y:2019,h:"#FF6F61"},
 {n:"Classic Blue",c:"19-4052",y:2020,h:"#0F4C81"},
 {n:"Very Peri",c:"17-3938",y:2022,h:"#6667AB",t:"The first Color of the Year invented new for the occasion"},
 {n:"Viva Magenta",c:"18-1750",y:2023,h:"#BB2649",s:{hist:"Pantone described it as rooted in cochineal, the insect red prized since the Aztecs."}},
 {n:"Peach Fuzz",c:"13-1023",y:2024,h:"#FFBE98"},{n:"Mocha Mousse",c:"17-1230",y:2025,h:"#A47864"},
 {n:"Cloud Dancer",c:"11-4201",y:2026,h:"#F0EEE9",t:"A soft off-white picked for 2026"}
 ]},
{ id:"japan", lv:6, title:"World traditions", school:"Japanese traditional colors", blurb:"Japan has hundreds of traditional color names drawn from plants, birds and dyes. Screen values are approximate.",
 cards:[
 {n:"Sakura",h:"#FEDFE1",tr:"cherry blossom",s:{cult:"Hanami, cherry-blossom viewing, celebrates beauty that lasts only days.",mind:"Tied to mono no aware, a gentle sadness at the passing of things."}},
 {n:"Fuji",h:"#8B81C3",tr:"wisteria"},{n:"Ruri",h:"#005CAF",tr:"lapis lazuli"},
 {n:"Kurenai",h:"#CB1B45",tr:"safflower crimson",s:{hist:"Dyed from safflower petals; a costly red in the Heian court."}},
 {n:"Uguisu",h:"#6C6A2D",tr:"bush warbler",s:{hist:"Named after the dull olive feathers of the Japanese bush warbler."}},
 {n:"Kohaku",h:"#CA7A2C",tr:"amber"},{n:"Asagi",h:"#33A6B8",tr:"pale green-onion"},
 {n:"Ai",h:"#165E83",tr:"indigo",t:"So common in Japan that a British chemist called it Japan Blue",s:{hist:"Japanese indigo dyeing spread widely in the Edo period. Visiting chemist Robert Atkinson called it Japan Blue in the 1870s."}},
 {n:"Kon",h:"#0F2540",tr:"deep navy indigo"}
 ]},
{ id:"hex", lv:7, title:"Pro: read hex", school:"Hex codes (Photoshop)", hex:true, blurb:"#RRGGBB is three pairs: red, green, blue. 00 is none, FF is full, 80 is about half. Equal pairs make a grey. Learn the anchors and you can read any code.",
 cards:["#FF0000","#00FF00","#0000FF","#000000","#FFFFFF","#808080","#FFFF00","#00FFFF","#FF00FF","#FF8000","#80FF00","#8000FF","#800000","#FF8080","#000080","#8080FF","#008000","#80FF80"].map(h=>({n:h,h}))}
];
const SCHOOL_HISTORY = {};
