#!/usr/bin/env python3
"""Find one free image per Botany entry on Wikimedia Commons (prefers old botanical illustrations), hotlinked.
Writes data/botany-images.js: window.BOTANY_IMAGES = { "<node id>": [ {src, w, h, alt, caption, credit, license, licenseUrl, commons} ] }.
Polite: descriptive User-Agent, one request at a time, cached in research/_raw/botany-images.json."""
import json, re, subprocess, time, urllib.parse, urllib.request
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
CACHE = ROOT / "research" / "_raw" / "botany-images.json"
UA = "ColorHubBot/1.0 (https://github.com/dmekibel/colorhub)"
API = "https://commons.wikimedia.org/w/api.php"
OK = re.compile(r"^(public domain|pd|cc0|cc by(-sa)? ?[0-9.]*)", re.I)

def api(**p):
    p.update(format="json", formatversion=2)
    req = urllib.request.Request(API + "?" + urllib.parse.urlencode(p), headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.load(r)

def find(term):
    for q in (f"{term} botanical illustration", f"{term} Köhler", term):
        res = api(action="query", generator="search", gsrsearch=f"filetype:bitmap {q}", gsrnamespace=6, gsrlimit=8,
                  prop="imageinfo", iiprop="url|extmetadata|size", iiurlwidth=800)
        pages = sorted((res.get("query") or {}).get("pages", []), key=lambda p: p.get("index", 99))
        for pg in pages:
            ii = (pg.get("imageinfo") or [{}])[0]; md = ii.get("extmetadata", {})
            lic = re.sub("<[^>]+>", "", md.get("LicenseShortName", {}).get("value", "")).strip()
            if not OK.match(lic) or ii.get("width", 0) < 300:
                continue
            artist = re.sub("<[^>]+>", "", md.get("Artist", {}).get("value", "")).strip()[:80] or "Unknown"
            return {"src": ii.get("thumburl"), "w": ii.get("thumbwidth"), "h": ii.get("thumbheight"), "lic": lic,
                    "licenseUrl": md.get("LicenseUrl", {}).get("value", ""), "commons": ii.get("descriptionurl"),
                    "artist": artist, "file": pg.get("title", "")}
        time.sleep(1)
    return None

def main():
    out = subprocess.run(["node", "-e", "global.window={};require('./data/botany.js');console.log(JSON.stringify(window.BOTANY))"],
                         cwd=ROOT, capture_output=True, text=True, check=True).stdout
    B = json.loads(out)
    cache = json.loads(CACHE.read_text()) if CACHE.exists() else {}
    jobs = []
    for p in B["plants"]:
        m = re.search(r"\(([^)]+)\)", p["plant"])
        jobs.append(("bt:plant:" + p["id"], (m.group(1) if m else p["plant"]).split(",")[0].strip(), p["plant"]))
    for d in B["dyes"]:
        m = re.search(r"\(([A-Z][a-z]+ [a-z]+)\)", " ".join(d.get("body", [])))
        jobs.append(("bt:dye:" + d["id"], m.group(1) if m else d["title"], d["title"]))
    # hand-picked search terms where the automatic one finds the wrong thing
    OVERRIDE = {"bt:plant:magenta": "Fuchsia magellanica", "bt:plant:tan": "Quercus robur bark", "bt:plant:amber": "Baltic amber",
                "bt:plant:chartreuse": "Chartreuse liqueur", "bt:plant:ash": "Fraxinus excelsior", "bt:dye:lichens-orchil": "Roccella tinctoria"}
    jobs = [(nid, OVERRIDE.get(nid, term), label) for nid, term, label in jobs]
    res = {}
    for nid, term, label in jobs:
        if nid not in cache:
            try: cache[nid] = find(term)
            except Exception as e: print("fail", nid, e); cache[nid] = None
            CACHE.write_text(json.dumps(cache, indent=1)); time.sleep(1)
        f = cache[nid]
        if not f: print("no image:", nid, term); continue
        res[nid] = [{"src": f["src"], "w": f["w"], "h": f["h"], "alt": label,
                     "caption": label + ". " + re.sub(r"^File:|\.[a-zA-Z]+$", "", f["file"])[:90],
                     "credit": f"{f['artist']} · {f['lic']}", "license": f["lic"], "licenseUrl": f["licenseUrl"], "commons": f["commons"]}]
    js = "// Botany images from Wikimedia Commons (hotlinked thumbnails; credit and license per image). Generated by tools/botany_images.py.\nwindow.BOTANY_IMAGES = " + json.dumps(res, ensure_ascii=False) + ";\n"
    (ROOT / "data" / "botany-images.js").write_text(js)
    print(len(res), "of", len(jobs), "entries have an image")

main()
