#!/usr/bin/env python3
"""One free specimen photo per gem without an image (Wikimedia Commons, hotlinked, credited).
Writes data/gem-images.js: window.GEM_IMAGES = { "gm:gem:<id>": [ {...} ] }. Reuses tools/botany_images.py's search."""
import json, re, subprocess, sys, time
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
ROOT = Path(__file__).resolve().parent.parent
CACHE = ROOT / "research" / "_raw" / "gem-images.json"
import importlib.util
spec = importlib.util.spec_from_file_location("bi", ROOT / "tools" / "botany_images.py")
src = (ROOT / "tools" / "botany_images.py").read_text().replace("\nmain()\n", "\n")
bi = {"__file__": str(ROOT / "tools" / "botany_images.py"), "__name__": "bi"}; exec(compile(src, "botany_images", "exec"), bi)
TERMS = {"ruby": "Ruby crystal", "sapphire": "Sapphire gem", "emerald": "Emerald crystal", "aquamarine": "Aquamarine crystal",
         "morganite": "Morganite", "amethyst": "Amethyst geode", "citrine": "Citrine quartz", "garnet": "Almandine garnet crystal",
         "peridot": "Peridot gem", "topaz": "Topaz mineral specimen", "tourmaline": "Watermelon tourmaline", "spinel": "Spinel crystal",
         "opal": "Precious opal", "pearl": "Natural pearl", "coral": "Corallium rubrum", "jet": "Whitby jet", "lapis-lazuli": "Lapis lazuli",
         "turquoise": "Turquoise mineral", "jade": "Jadeite", "malachite": "Malachite mineral", "azurite": "Azurite crystal",
         "cinnabar": "Cinnabar on dolomite", "amber": "Baltic amber insect", "diamond": "Rough diamond", "alexandrite": "Alexandrite",
         "tanzanite": "Tanzanite crystal", "moonstone": "Moonstone gem", "labradorite": "Labradorite", "rose-quartz": "Rose quartz"}
def find(term):
    for q in (term, term.split()[0]):
        res = bi["api"](action="query", generator="search", gsrsearch=f"filetype:bitmap {q}", gsrnamespace=6, gsrlimit=8,
                        prop="imageinfo", iiprop="url|extmetadata|size", iiurlwidth=800)
        for pg in sorted((res.get("query") or {}).get("pages", []), key=lambda p: p.get("index", 99)):
            ii = (pg.get("imageinfo") or [{}])[0]; md = ii.get("extmetadata", {})
            lic = re.sub("<[^>]+>", "", md.get("LicenseShortName", {}).get("value", "")).strip()
            if not bi["OK"].match(lic) or ii.get("width", 0) < 300: continue
            artist = re.sub("<[^>]+>", "", md.get("Artist", {}).get("value", "")).strip()[:80] or "Unknown"
            return {"src": ii.get("thumburl"), "w": ii.get("thumbwidth"), "h": ii.get("thumbheight"), "lic": lic,
                    "licenseUrl": md.get("LicenseUrl", {}).get("value", ""), "commons": ii.get("descriptionurl"), "artist": artist, "file": pg.get("title", "")}
        time.sleep(1)
out = subprocess.run(["node", "-e", "global.window={};require('./data/gems.js');console.log(JSON.stringify(window.GEMS))"], cwd=ROOT, capture_output=True, text=True, check=True).stdout
G = json.loads(out); have = set(G.get("images", {}))
cache = json.loads(CACHE.read_text()) if CACHE.exists() else {}
res = {}
for g in G["gems"]:
    nid = "gm:gem:" + g["id"]
    if nid in have: continue
    if nid not in cache:
        try: cache[nid] = find(TERMS.get(g["id"], g["title"]))
        except Exception as e: print("fail", nid, e); cache[nid] = None
        CACHE.write_text(json.dumps(cache, indent=1)); time.sleep(1)
    f = cache[nid]
    if not f: print("no image:", nid); continue
    res[nid] = [{"src": f["src"], "w": f["w"], "h": f["h"], "alt": g["title"],
                 "caption": g["title"] + ". " + re.sub(r"^File:|\.[a-zA-Z]+$", "", f["file"])[:90],
                 "credit": f"{f['artist']} · {f['lic']}", "license": f["lic"], "licenseUrl": f["licenseUrl"], "commons": f["commons"]}]
(ROOT / "data" / "gem-images.js").write_text("// Gem photos from Wikimedia Commons (hotlinked thumbnails; credit and license per image). Generated by tools/gem_images.py.\nwindow.GEM_IMAGES = " + json.dumps(res, ensure_ascii=False) + ";\n")
print(len(res), "new images")
for k, v in res.items(): print(k.ljust(22), v[0]["caption"][:90], "|", v[0]["license"])
