"""Hand-paraphrased origin/etymology facts from the "Notes on Color Names" (pp. 137-188) of
Maerz & Paul, *A Dictionary of Color* (1930).  Original wording is NOT copied; each entry is a short
paraphrase of what the authors report.  Used by tools/mp_dictionary.py.

Each tuple: (names the note covers, short fact, year the note itself dates the word or None).
Names are matched case-insensitively against index names.
"""
NOTES = [
    (["Acajou"], "French word for mahogany; the authors treat it as a plain synonym of Mahogany.", None),
    (["Alkanet"], "From Arabic al-henneh via al-kanna, first the name of a shrub; the European dye plant Anchusa tinctoria took the name. An ancient, minor dyestuff known to the Romans, giving violet and greyish tones.", None),
    (["Alyce", "Couleur d'Alyce"], "Anglicized from French alize or alise, the serviceberry, whose fruit runs from red to dark violet. A 1705 English dyeing manual describes it as a brown violet.", 1705),
    (["Angel Red"], "A drifted form of French Rouge d'Angleterre ('English red'), the old name for the iron-oxide pigment colcothar.", None),
    (["Azure"], "Through Romance languages and medieval Latin from Arabic al-lazward or Persian lajward, 'lapis lazuli'; in practice only a literary synonym for blue, never a specific blue.", None),
    (["Ecru"], "French for the raw, undyed state of cloth, from e- plus cru, Latin crudus 'raw'; hugely modish until about 1910, then nearly obsolete.", None),
    (["Beige"], "French dye-house term for undyed wool cloth, from an old dialect word meaning grey (cf. Italian bigio); a modish color word only from the later 1800s.", None),
    (["Grege", "Grège"], "French for raw, unbleached cloth; originally meant grey, probably from Italian greggia/grigio, ultimately Germanic.", None),
    (["Bice", "Blue Bice", "Verditer", "Blue Verditer"], "Names for a blue pigment made from basic copper carbonate, long confused with true ultramarine; 'bice' is a medieval-Latin abbreviation of 'debilis' (weak blue); 'verditer' is French verd de terre in an old, incorrect derivation, really from verdetre 'greenish'.", None),
    (["Cendre Blue"], "Cendre is French for ashes; an old, very common name for a pale copper-based blue pigment.", None),
    (["Bistre"], "A brown pigment made from chimney soot; a French word related to bis/bise 'brown', traced to the 1500s (bis to the 1000s).", None),
    (["Blood-Orange", "Blood Orange"], "A textile color popular in the later 19th century; the authors could not find a sample, so it is unknown whether it meant the peel or the flesh.", None),
    (["Bordeaux"], "Arose in English in the 19th century as a mere synonym of Claret; named for the French wine city of Bordeaux, whose red wines gave claret its sense.", 1905),
    (["Claret"], "From Old French clairet, a diminutive of clair 'clear, light'; first only for light-red wines, then (about 1600) for red wines generally.", 1600),
    (["Brazilwood"], "Dye tree of the genus Caesalpinia; the country was named after the tree, not the reverse. Brazil, from Italian or Spanish for 'glowing coals', was in use centuries before America was reached.", None),
    (["Brewster Green"], "A Victorian coach color, still used on automobile bodies; a very dark green.", None),
    (["Brown"], "From Anglo-Saxon brun, from a root meaning 'burned'.", None),
    (["Brown Bread"], "Named from the crust of the old rye-flour brown bread, not the later American Boston brown bread.", None),
    (["Brunswick Green", "Chrome Green"], "Chrome green originally meant chromium oxide; in America it came to mean a mixture of chrome yellow and Prussian blue. Brunswick green may contain over 60 per cent barytes.", None),
    (["Buff"], "From buffalo (Italian bufalo, Greek boubalos, the Old World ox); originally the yellowish-brown color of soft oil-tanned leather used for soldiers' uniforms.", None),
    (["California Color"], "A shade popular in the early 19th century, dyed in light, medium and dark tones.", None),
    (["Capri Blue"], "Named after the island of Capri and its Blue Grotto; Ridgway's earlier Capri Blue named a coal-tar dye found by Bender in 1890.", 1890),
    (["Carnation"], "From Latin carneus 'flesh-colored'; used in English for flesh color from 1535. By 1597 writers mistakenly derived it from the flower; before the 20th century Carnation always meant flesh color.", 1535),
    (["Carrot Red"], "A very old term, earliest record found 1684, though the color is really a yellow-orange.", 1684),
    (["Cauldron", "Caldera", "Chaudron"], "Caldera is Spanish and Chaudron French for a copper kettle; the color is that of oxidized or polished copper.", None),
    (["Cendre Green", "Green Ashes"], "Name of an inferior, duller and greener azurite blue (cendre is French 'ashes'); later misapplied to malachite green.", None),
    (["Cerise"], "French for cherry, but from the start used for a color unlike the fruit; earliest English record found 1858 (Wilkinson: 'not the colour of a cherry').", 1858),
    (["Chestnut"], "Used for nearly 400 years as the color of the edible chestnut shell; Wilkinson (1858) called it lighter than the Spanish chestnut fruit.", 1858),
    (["Chinese Blue"], "Name of one of the best grades of Prussian blue, dating from the early 19th century.", None),
    (["Cinnabar", "Zinnober"], "From Latin via Greek, for the mineral mercuric sulphide (vermilion when ground), at least 2,500 years old as a name.", None),
    (["Citrine"], "From Latin citrinus 'lemon-colored'; in French by the 11th century and in English in the 14th (international since at least 1386). George Field's 19th-century color scheme turned it from lemon to an olive-brownish tertiary.", 1386),
    (["Cloth Color"], "A term common in early 18th-century New England records; unidentified, possibly undyed cloth or indigo blue. Cloth is from Anglo-Saxon clath.", None),
    (["Colibri"], "From a Carib word for the hummingbird, used in English and French in this spelling for over 200 years.", None),
    (["Colonial Buff"], "An invented paint-trade name by analogy with Colonial Yellow; not the buff of the Revolutionary War uniforms.", None),
    (["Colonial Yellow"], "A fairly old name in the mixed-paint industry whose actual color has drifted widely.", 1893),
    (["Cornflower", "Bluet"], "Bluet is just the French word for cornflower.", None),
    (["Crimson", "Carmine"], "Both from medieval Latin cremesinus/kermesinus/carmesinus, 'of the kermes insect', the source of the original bluish-red dye and of scarlet; after cochineal was found, the dye came from it. 15th-century English spelled it cremesin.", None),
    (["Crushed Strawberry"], "Hugely popular in the later 19th century.", None),
    (["Cyaneous"], "From ancient Greek kyanos; Homer used it 45 times for dark blue, sometimes just 'dark'. Etymology undetermined.", None),
    (["Delft Blue"], "Named for Delft, Holland, where potters about the start of the 18th century first imitated this blue from imported Chinese porcelain; it was first called 'Oriental Blue'.", 1700),
    (["Duck's Egg Green", "Duck's Egg"], "A name that arose about 1876, used mainly in English mixed paint.", 1876),
    (["Dun"], "A very old term, taken into Old English from a Celtic language before 900; used from about 1000 (ass-dun) for dull brownish greys of mice, cows and asses.", 1000),
    (["Eggshell Blue", "Eggshell Green"], "British paint names that match the American Robin's Egg Blue.", None),
    (["Electric Blue", "Electric Green"], "Had an immense vogue in the later 19th century; the genuine color is the one originated in 1892.", 1892),
    (["Elephant's Breath"], "A famous, widely recorded name for which the authors could never find an authentic sample.", None),
    (["Emeraude"], "Simply French for emerald; also given to the pigment transparent oxide of chromium.", None),
    (["Eton Blue", "Cambridge Blue", "Oxford Blue"], "Eton Blue is the older, from the 15th century; Cambridge adopted it for the university boat in 1836. Oxford Blue is the dark blue of the Thames boat race.", 1836),
    (["Extract of Vermilion"], "Formerly used in paints; just ordinary vermilion with a sales-minded name.", None),
    (["Feuille Morte"], "French for 'dead leaf'; a dark orange-brown, the color of leaves just fallen and not yet soiled.", None),
    (["Flame", "Flame Scarlet"], "A very old, widespread color name, dating from as early as 1590.", 1590),
    (["Flint Grey"], "One of the oldest color terms in English, from the earliest Anglo-Saxon period; flint is silica found in chalk beds.", None),
    (["Flower de Luce Green"], "A popular 17th-century pigment made from fermented blue-flag iris flowers and alum; Flower de Luce is an old spelling of fleur de lis. Later called Iris Green.", None),
    (["French Grey"], "First recorded by Patrick Syme in his 1814 edition of Werner's Nomenclature of Colours (Edinburgh).", 1814),
    (["Gaudy Green", "Gaude Green"], "Not 'flashy': made with gaude, the French word (Germanic walda) for weld, Reseda luteola, source of Europe's oldest known dye; dyed first in indigo, then in weld.", None),
    (["Gay Green"], "Not a cheerful green: an English form of the old French verde gay, short for verde papegai 'Popinjay Green', from Greek papagas 'parrot'.", None),
    (["Gendarme Blue"], "An old French color from the 19th century or before, taken from parts of the French gendarmes' uniform.", None),
    (["Glaucous"], "From ancient Greek; Homer used it for a gleam (lion's eyes, the sea), later Greek and Roman writers for an indefinite pale grey blue-green.", None),
    (["Glowworm"], "French equivalent Luciole appears in a 1892 list of textile colors.", 1892),
    (["Gold", "Old Gold"], "Gold and yellow share one origin, from a primitive Indo-European root ghel meaning yellow; matched by the authors against real gold plate.", None),
    (["Goldenglow", "Golden Glow"], "Presumably named for the flower, a cut-leaf coneflower (Rudbeckia laciniata).", None),
    (["Golden Green"], "A literary term of the last century for foliage seen in the light of the setting sun.", None),
    (["Golden Red"], "A literary term with no exact color meaning; any orange-toned red.", None),
    (["Grass Green"], "One of the oldest color names, recorded as early as 700 in Old English and found in most languages.", 700),
    (["Grenadine Red", "Grenadine"], "Named in Oberthur's 1905 Repertoire for the color of the Grenadine liqueur, an international term.", 1905),
    (["Gunmetal"], "In use for some sixty years by 1930.", None),
    (["Havana", "Havana Brown"], "In use since a little after the middle of the 19th century, for the brown of a Havana cigar.", 1850),
    (["Hazel"], "A very old color name, the shell of the ripe hazelnut (the nut is also called filbert).", None),
    (["Heather"], "Before 1918 meant a mottled or speckled appearance; the Textile Color Card Association first made it a specific color in 1918.", 1918),
    (["Hedge Sparrow Egg"], "In use for over a hundred years; the color of the hedge sparrow's egg.", None),
    (["Hunter Green", "Hunter's Green"], "Old and widely used, in French Chasseur: a dark, dull green once worn by hunters.", None),
    (["Ivy", "Ivy Green"], "Named for ivy leaves; French equivalent is Lierre.", None),
    (["Jade Green", "Jade"], "Jade comes from the Spanish piedra de ijada 'colic stone', first used about 1569; it was proved only in 1865 that two minerals (jadeite and nephrite) had been confused under the name.", 1569),
    (["Khaki"], "From Urdu khaki 'dust-colored'; first used by British troops in India in 1848.", 1848),
    (["Lake"], "From East Indian lac or lakh 'a hundred thousand', for the lac insects whose secretion gave a red dye; Italian painters of the 1500s applied lacca to lake pigments generally.", None),
    (["Lavender", "Lavender Blue", "Lavender Grey"], "Arose toward the end of the 17th century as Lavender Grey, later Lavender Blue, for the color of the lavender flower; the generic word was dropped and Lavender alone became a color only by the mid-19th century. A 1705 dyeing manual uses Lavender Grey.", 1705),
    (["Lead", "Lead Grey"], "French equivalent Gris de Plomb; the color of lead used for building, weathered or new.", None),
    (["Leather", "Tan"], "Leather appears as a color term in a 1892 list; Tan is a very old term for the color of oak-tanned ox hide, from colloquial Latin tannum, possibly Celtic.", 1892),
    (["Lilac"], "As a color name dates from the middle of the 18th century.", 1750),
    (["Lime Blue"], "A formerly wide-used fresco pigment of copper hydroxide and calcium sulphate, now obsolete.", None),
    (["Lime Green", "Vert Tilleul", "Linden Green"], "'Lime' has been taken from two trees: the citrus lime fruit, and the winged seed of the European linden (lime tree); French Vert Tilleul is the linden one.", None),
    (["Livid"], "From Latin lividus, 'dull leaden blue'; also the color of a bruise ('black and blue').", None),
    (["Louise Blue", "Louisa Blue"], "Often given as a synonym of Prussian blue, but old pattern books show it was dyed with indigo extract and a trace of cochineal.", None),
    (["Lumiere Green", "Lumière Green", "Vert Lumiere", "Vert Lumière"], "A green vegetable dye called Chinese Green or lo-kao was brought from China to Europe in 1852; in 1853 it gave France three greens, Vert Lumiere, Vert-Venus and Vert-Azof.", 1853),
    (["Lurid"], "From Latin luridus, 'sallow, dirty yellow'; first used in English as early as 1656, later for stormy skies; in 1871 used for a dark purplish color.", 1656),
    (["Luteous"], "From Latin lutum, weld; came to mean yellow of reddish tones.", None),
    (["Mahogany", "Mahogany Red", "Mahogany Brown"], "Named for the reddish-brown wood; much imitation mahogany is stained wood, often garish.", None),
    (["Malachite Green"], "A natural copper carbonate pigment used for over 3,000 years; from ancient times to the Renaissance it was called chrysocolla (Greek), later Mountain Green, Bice Green, Oil Green.", None),
    (["Mallow", "Mallow Purple", "Mauve"], "Mallow Purple has been in use since 1611, for the flower of the common mallow; mauve is the French cognate for mallow, later given to Perkin's first coal-tar dye of 1856, first called Perkin's Violet.", 1611),
    (["Mandarin Orange", "Mandarin Red"], "Came into use before 1883, from the color of the mandarin fruit (Citrus nobilis); later also given to a coal-tar dye.", 1883),
    (["Marigold"], "In use as a color term for over 200 years; the flower is Tagetes erecta.", None),
    (["Maroon"], "This spelling dates from the close of the 18th century; earlier forms were Italian marrone (chestnut), marone, French marron; refers to the large Spanish chestnut.", 1799),
    (["Mauvette"], "Used by Ridgway in 1912.", 1912),
    (["Merroon"], "An unexplained spelling used by Bemiss in 1806, 'brighter than madder'; possibly from French mouron (red pimpernel) or muron (raspberry).", 1806),
    (["Milk White", "Skimmed Milk White"], "Patrick Syme changed Werner's 'Milk White' to 'Skimmed Milk White' in his 1814 Edinburgh edition, a white tinged with a little Berlin blue and ash grey.", 1814),
    (["Mineral Brown", "Metallic Brown"], "Long used for any native earth colored by iron oxide, so not a specific color.", None),
    (["Minim"], "Said to be the color of Franciscan monks' habits in the 17th century; not identified by the authors.", None),
    (["Mode"], "A 19th-century French class of colors (gris mode) dyed from mixed red, yellow and blue dyes, giving pale to tinted greys much like modern pastels.", None),
    (["Morocco", "Morocco Red", "Moroccan", "Marocain"], "The color of Moroccan leather (French marroquin, the leather, since the 1500s); standardized in Oberthur's 1905 Repertoire.", 1905),
    (["Moss Green", "Old Moss Green"], "Oberthur's Repertoire (1905) took the green from young Hypnum moss, and Old Moss Green from older moss.", 1905),
    (["Mouse"], "First used as Mouse-dun about 1420; Anglo-Saxon had mus fealo, 'mouse fallow'; the bare word Mouse as a color name came about 1600.", 1420),
    (["Mulberry", "Murrey"], "Murrey has been an English color term for over 500 years, from Old French moree, Latin morus, Greek moron 'mulberry'.", None),
    (["Mummy Brown", "Mummy"], "A pigment dating from the 16th century, really asphaltum; said to come from mummy cases, though that is doubted.", 1550),
    (["Nacarat de Bourre", "Flock Red"], "Made by dyeing goat's hair in madder, then dissolving it in potash; a fugitive reddish-orange of poor quality.", None),
    (["Navy Blue", "Marine Blue"], "Adopted in the early 19th century from sailors' uniforms; first called Marine Blue, soon Navy Blue; dyed with indigo. French Matelot ('sailor') entered English about 1895.", 1895),
    (["Night Green"], "Originally a coal-tar dye found by Keisser in 1866, so called because it stayed green under gaslight.", 1866),
    (["Nut Brown"], "As a color term dates from 1300 and doubtless earlier; Chestnut was used by 1555, Hazel 1592 and Walnut 1705.", 1300),
    (["Nut Grey"], "Described in Hellot's 1798 dyeing manual; made in a bath of fustic, archil, logwood and copperas.", 1798),
    (["Nymphea"], "French word from Latin nymphaea, Greek nymphaia, 'water-lily'.", None),
    (["Ochre"], "From ancient Greek ochros; Homer paired it with chloros for the pale face of fear; later the yellowish native clay earth, one of the oldest pigments.", None),
    (["Old Blue", "Bleu Passe", "Bleu Passé", "Blue Passe"], "French passe means 'old' or faded, so Bleu Passe is Old Blue translated.", None),
    (["Old Rose"], "Arose in the Victorian era and became one of the most popular of all color names.", 1850),
    (["Olive Brown", "Olive Passee", "Old Olive"], "Oberthur's Olive Passee is the dull yellowish-brown of a ripe olive after long preserving.", 1905),
    (["Olive Green", "Olive"], "The traditional color of the green olive.", None),
    (["Opal Blue"], "Originally a dye-trade synonym of Bleu de Lyon.", None),
    (["Orange"], "From the citrus fruit, in both name and color; the word has long since come to mean a whole class of colors in the spectrum.", None),
    (["Otter", "Loutre"], "English and French animal names that came into use as colors toward the end of the 19th century.", 1890),
    (["Oxblood"], "Names a variety of Chinese ceramic glaze, a case where a color name was fixed on something other than the substance named.", None),
    (["Oxford", "Oxford Grey"], "In common use for a century (by 1930), originally the color of oxford cloth, a dark grey.", None),
    (["Pansy", "Heartsease"], "Heartsease has been applied to the pansy since the 16th century.", 1550),
    (["Parma", "Parme", "Parma Violet"], "Parma is a province of northern Italy; Parme is the French spelling, from the horticultural Parma violet (Viola parmensis); the 19th-century color was dyed with orchil.", None),
    (["Parrot Green", "Parrot", "Parrakeet", "Parroquit Green"], "Parrot Green dates from 1646; Parroquit Green appears as an alternate in 1705; parrakeet is an English phonetic spelling of French perroquet.", 1646),
    (["Pastel Blue", "Pastel"], "Originally the blue of the dye from the pastel plant (Isatis tinctoria, a French name for woad), only later confused with pastel crayons.", None),
    (["Pea Green"], "A fairly old term used mostly in the paint industry; French Vert Pois.", None),
    (["Peach"], "A color name in use since the 16th century.", 1550),
    (["Peach Blossom"], "For over 200 years the pure, tender pink of the peach tree in bloom.", None),
    (["Pearl White", "Pearl", "Pearl Blue", "Pearl Grey"], "First recorded as Pearl White in 1590, Pearl in 1604, Pearl Blue in 1669 and Pearl Grey in 1705; unclear whether early uses meant the gem or mother-of-pearl.", 1590),
    (["Pers", "Perse"], "Recorded in English as early as 1366 as a plain synonym for 'blue'; the 17th-century 'Persian Blue' came from this word, not from Persia.", 1366),
    (["Pervenche"], "French word for the periwinkle flower (Vinca minor); used as an English color term before 1892.", 1892),
    (["Philomel Yellow"], "From philomel, a poetic word for the nightingale (Greek philomela); a color about 1865 for which no sample survives.", 1865),
    (["Pink", "Pinke"], "The pale-red 'pink' has an unknown origin; in the 16th century pink and pinke named yellow pigments (Dutch Pink, English Pink, Italian Pink).", None),
    (["Pistachio Green", "Pistachio", "Pistache"], "A fairly old color name, as early as 1789; the color of the kernel inside the nut. French pistache was adopted late in the 19th century.", 1789),
    (["Pitch Black"], "A very old term; used as a simile ('black as pyk') as early as 1303.", 1303),
    (["Pomegranate"], "In the early 17th century the flower's color was called Granate or Pomegranate Blossom; only later was the fruit's color used for Pomegranate.", 1600),
    (["Pompeian Red"], "Named for the red of the frescoes of Pompeii villas; popular for the half-century before 1930.", None),
    (["Ponceau", "Coquelicot", "Poppy"], "Ponceau is the French name of the corn poppy, with coquelicot (an imitation of the cock's crow, alluding to the comb); Coquelicot entered English in 1795, Ponceau about 1835; Poppy has been in English for over 200 years.", 1795),
    (["Portland Stone"], "Used by several British paint makers since about 1820.", 1820),
    (["Powder Blue"], "In use as early as 1707, a translation of old French poudre bleue, meaning 'blue powder' (smalt, powdered cobalt blue glass).", 1707),
    (["Prasine", "Prasinous"], "From Greek prasinos, the general word for green after Homer, usually glossed 'leek green'.", None),
    (["Primrose Yellow", "Primrose"], "In use for over 300 years; the color of the common English primrose.", None),
    (["Prussian Blue", "Berlin Blue"], "Berlin Blue was the original name; the pigment was discovered in 1704, first described in Germany in 1710 and in English in 1724.", 1704),
    (["Prussian Green"], "Originally a poor paint made by mixing Prussian blue with yellows.", None),
    (["Purple"], "The mixture of red and blue, from Greek; a class of colors, not one tone.", None),
    (["Putty"], "The color of the putty used by painters; average mixed-paint shade.", None),
    (["Quaker Grey", "Quaker Drab", "Quaker"], "The Quakers never adopted one specific color; they required only dull, unobtrusive colors, mainly greys and browns, from the mid-17th century.", None),
    (["Ragged Sailor"], "A popular name for the cornflower or bluet.", None),
    (["Raisin", "Raisin Black"], "Named for the dried grape; Ridgway took Raisin Black from Oberthur.", None),
    (["Raw Sienna", "Siena", "Sienna"], "Earth pigment named for Siena, Italy; the textile term Siena appears as early as 1874.", 1874),
    (["Reseda", "Mignonette"], "In English since at least 1875; simply the French word for the mignonette flower, Reseda odorata.", 1875),
    (["Robin's Egg Blue", "Robin's Egg"], "The color of the egg of the American robin, a bird unrelated to the English robin.", None),
    (["Rose", "Rose Red", "Rose Pink"], "The rose was the first cultivated flower; Sappho crowned it queen of flowers some seven centuries before Christ.", None),
    (["Rose de Nymphe"], "Oberthur's name, said to allude to the imagined flesh color of the nymphs of mythology.", 1905),
    (["Rosewood", "Palissandre", "Jacaranda Brown"], "Two different Brazilian woods both called rosewood gave color names; the Brazilian name for one is jacaranda, the French palissandre.", None),
    (["Russet"], "From Old French rousset, a diminutive of rous, from Latin rossus 'reddish'; first a rough reddish-brown homespun cloth (by 1400), a color term from about 1562.", 1400),
    (["Sage", "Sage Green", "Sage Grey"], "Recorded in 1596 for the foliage of garden sage (Salvia officinalis); Sage Green appears about 1800 and Sage Grey about 1700.", 1596),
    (["Salmon"], "A fairly old, well-established color; Oberthur describes it as the color of the fish's flesh.", None),
    (["Saxe Blue", "Saxon Blue", "Saxony Blue", "Bleu de Saxe"], "Saxe is French for Saxony; Saxony Blue was a synonym for smalt as early as 1550, and since 1753 Saxon Blue has meant indigo extract.", 1550),
    (["Scarlet", "Scarlet Red"], "Found in Romance and Germanic languages from at least the early 13th century; the origin is obscure, perhaps Persian saqalat, a red cloth dyed with kermes.", 1200),
    (["Sea Green"], "Sea color varies widely; Ridgway's 'Sea Green' is really a sea blue.", None),
    (["Sepia"], "From Latin and Greek for the cuttlefish whose ink gave the pigment; used as ink in ancient times but too fugitive for paint.", None),
    (["Shrimp", "Prawn", "Crevette"], "Prawn Pink was used as a color as early as 1839; Crevette is the French word.", 1839),
    (["Silver", "Silver Grey", "Old Silver"], "As a color term Silver dates from 1481, Silver Grey from 1607.", 1481),
    (["Sky Grey"], "The even grey of an overcast sky.", None),
    (["Slate Grey", "Ardoise"], "Oberthur's Ardoise, French for slate, was Englished as Slate Grey.", 1905),
    (["Slate-Violet", "Slate Violet", "Violet ardoise"], "A name used in both English and French (violet ardoise).", 1905),
    (["Smalt"], "Powdered blue glass colored with cobalt oxide; once in very wide demand, now obsolete outside glass painting, enamel and ceramics.", None),
    (["Snow White"], "Used since antiquity for the purest white.", None),
    (["Snuff Brown", "Snuff"], "A fairly old color name, in use since the 17th century.", 1600),
    (["Steel Blue"], "An old, established name for a grade of Prussian blue.", None),
    (["Stil de grain"], "Derivation unknown; the genuine pigment (also called Dutch, English or Italian Pink) is a lake made from buckthorn berries.", None),
    (["Taupe"], "Originated in France in the early 19th century and was adopted into English at once; French for 'mole', the animal.", 1800),
    (["Tawny"], "A phonetic English spelling of French tanne 'tan-colored', adopted in the 14th century (also tenne, tenny); later chiefly the color of animals such as the lion.", 1300),
    (["Tea Rose"], "A color name as early as 1884.", 1884),
    (["Terra Cotta"], "From Italian, 'baked clay'.", None),
    (["Terra Verte"], "A very ancient pigment, 'green earth': a clay colored by green hydrated iron oxide, found all over the world.", None),
    (["Terra Columbiana"], "Name in certain colonial documents for a natural ochre deposit that was never worked.", None),
    (["Terra Brown"], "A coined mixed-paint name; terra is Italian for earth.", None),
    (["Thistle", "Thistle Bloom", "Thistletuft"], "Textile names for near-identical thistle-flower colors.", None),
    (["Tobacco", "Tobacco Brown"], "An old term, in use since 1789 and doubtless earlier; tobacco colors vary too much to define one color.", 1789),
    (["Tomato Red"], "Named for the ripe tomato.", None),
    (["Tyrian Purple"], "One of the most famous colors in history, traditionally from sea-snails such as Murex brandaris (following Pliny); the exact ancient method is probably not recovered.", None),
    (["Umber"], "A dark earth pigment, raw or burnt, whose colors vary with the source.", None),
    (["Venet"], "A 15th-century color term (a writer of 1425 called it 'watercolour'); shortened from medieval Latin venetus, 'Venice blue'.", 1425),
    (["Verbena", "Vervain"], "Verbena was taken into English from Latin, Vervain from Old French verveine; both name the same flower.", None),
    (["Verdigris", "Vert-de-gris"], "From Old French vertegrez, literally 'Greek green'; a pigment made since ancient times by corroding copper with wine lees or vinegar.", None),
    (["Veronese", "Veronese Green"], "Two different pigments carry the name: Paul Veronese Green is emerald green, Veronese Green is chromium oxide green.", None),
    (["Vinous", "Vinaceous"], "Latin-formed words meaning 'of wine' that were never color terms in Latin; as color names Vinaceous dates from the 17th century, Vinous from the 19th.", 1600),
    (["Viridine Green", "Viridian Green", "Viridene"], "Earliest record as a color is in Warhurst, 1899, as a synonym of emerald; Viridene was also a coal-tar green dye of 1878.", 1899),
    (["Vivid Green"], "Vivid is only a synonym of bright, so a poor name for one color.", None),
    (["Walnut", "Walnut Brown"], "Originally the color of the shell of the English walnut (Juglans regia).", None),
    (["Wedgwood Blue"], "Josiah Wedgwood made two blues in his ware, a dark and a light blue.", None),
    (["Wedgwood Green", "Wedgwood Grey"], "First recorded as general color names in Jennings.", 1926),
    (["Wine", "Wine Red"], "In English since before 1700 as a color term; Wine Red has been a common synonym for at least a century.", 1700),
    (["Wistaria"], "Named for the wisteria flower.", None),
    (["Wood Brown"], "First used in 1805, not for tree wood but for the mineral asbestos, then called 'mountain wood'; explained in Syme's 1814 book.", 1805),
    (["Wood-pigeon Grey"], "An obsolete name; no samples exist.", None),
    (["Yale Blue"], "Named for Yale University; its meaning varies widely among color cards.", None),
]
