#!/usr/bin/env python3
"""Rank the full article corpus for the DEPTH WAVE (design/articles-depth-brief.md), producing
design/articles-depth-queue.json.

    python3 tools/rank_depth_queue.py [--out design/articles-depth-queue.json]

Combines two things tools/depth_kit.py --rank-all already computes per article (an available-
material score, 0-100, and the current tier/depth/words) with a cheap reader-likelihood signal this
script adds on top:

  is_learn_word      in the ~1,000-name Learn curriculum (data/graph/names.json list code 'c') --
                      the single strongest signal: every Learn-path user meets this name.
  archive_n          how many paintings in our own 23,778-painting archive carry the color --
                      "painting usage" per the brief; a color nobody's photo-archive shows is a
                      color few readers will stumble into from that side either.
  link_centrality    inbound link-graph degree: how many OTHER articles' real look-alike edges
                      (la), named variants (kids) or cross-system aliases (also_of/trad_of) point
                      AT this slug. A color with many inbound edges is the one readers land on
                      from elsewhere, not just from its own page.

Only articles below long/epic are ranked (an already-long or -epic article does not need the wave);
the 12 pilot slugs are excluded (already done). Each entry gets a reader_likelihood (0-100, capped
contributions summed), the material score from depth_kit, and a combined priority score. Entries are
split into three tiers by priority for the wave's own sequencing.
"""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
import depth_kit  # noqa: E402

PILOTS = {"aero", "scheele-s-green", "payne-s-grey", "van-dyke-brown", "hathi-grey", "tiffany-blue",
          "rebecca-purple", "ash-rose", "battleship-grey", "pompeian-red", "ruber", "grey-green"}
NOT_THIN = {"long", "epic"}  # already deep enough; skip for this wave


def link_centrality():
    """slug -> inbound degree: how many other nodes' la/kids/also_of/trad_of name this slug."""
    import string
    counts = {}

    def bump(s):
        if s:
            counts[s] = counts.get(s, 0) + 1

    for c in string.ascii_lowercase:
        p = ROOT / "data" / "graph" / f"edges-{c}.json"
        if not p.exists():
            continue
        for e in json.loads(p.read_text(encoding="utf-8")):
            for item in e.get("la") or []:
                bump(item[0])
            for s in e.get("kids") or []:
                bump(s)
            for s in e.get("also_of") or []:
                bump(s)
            for s in e.get("trad_of") or []:
                bump(s)
    return counts


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(ROOT / "design" / "articles-depth-queue.json"))
    a = ap.parse_args()

    rows = depth_kit.rank_all()
    centrality = link_centrality()

    out = []
    for r in rows:
        slug = r["slug"]
        if slug in PILOTS or (r.get("depth") in NOT_THIN):
            continue
        cen = centrality.get(slug, 0)
        reader_likelihood = min(100, (40 if r["is_learn_word"] else 0) +
                                 min(30, r["archive_n"] / 20) + min(30, cen * 2))
        priority = round(0.55 * reader_likelihood + 0.45 * r["score"], 1)
        out.append({
            "slug": slug, "name": r["name"], "tier": r["tier"], "depth": r["depth"],
            "words": r["words"], "is_learn_word": r["is_learn_word"], "archive_n": r["archive_n"],
            "link_centrality": cen, "book_hits": r["book_hits"], "material_score": r["score"],
            "suggested_depth": r.get("suggested_depth"),
            "reader_likelihood": round(reader_likelihood, 1), "priority": priority,
        })
    out.sort(key=lambda x: -x["priority"])
    for i, row in enumerate(out):
        row["rank"] = i + 1
        row["wave_tier"] = 1 if i < 150 else 2 if i < 600 else 3

    Path(a.out).write_text(json.dumps({
        "_doc": "Generated by tools/rank_depth_queue.py. Ranked queue for the article DEPTH WAVE "
                "(design/articles-depth-brief.md), ordered by priority = 0.55*reader_likelihood + "
                "0.45*material_score. Excludes the 12 depth-wave pilot slugs (already done) and any "
                "article already long/epic. wave_tier 1 = first ~150 by priority, 2 = next ~450, "
                "3 = the rest.",
        "generated_from": "tools/depth_kit.py --rank-all + tools/rank_depth_queue.py link_centrality",
        "n": len(out),
        "tier_counts": {str(t): sum(1 for r in out if r["wave_tier"] == t) for t in (1, 2, 3)},
        "queue": out,
    }, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    print(f"wrote {a.out}: {len(out)} queued")


if __name__ == "__main__":
    main()
