#!/usr/bin/env python3
"""Squint station data: spots in each painting whose lightness (CIELAB L*) is known.

  python3 tools/squint.py        # rewrites data/squint.js

Why precomputed: the drill needs the true L* at each marked spot. Reading pixels in the browser
(canvas getImageData) fails on file:// pages and on any image served without CORS, so the values are
measured here once, from the same local files the drill shows (img/paintings/*.jpg).

Method: shrink the painting to 300 px wide, convert to L*a*b* (sRGB, D65), and keep spots whose 7x7
neighbourhood is flat (L* standard deviation under 2.2), so a marker ring sits on one clear value.
Spots are spread out (at least 7% of the width apart). Each spot is [x per mille, y per mille, L*, C*].
"""
import json, os, re
from PIL import Image
import numpy as np

ROOT = os.path.join(os.path.dirname(__file__), "..")
src = open(os.path.join(ROOT, "data/paintings.js"), encoding="utf8").read()
items = re.findall(r'"id": "painting-([a-z-]+)", "title": "([^"]+)", "artist": "([^"]+)"[^}]*?"img": "([^"]+)"', src)

def to_lab(rgb):
    c = rgb / 255.0
    c = np.where(c > .04045, ((c + .055) / 1.055) ** 2.4, c / 12.92)
    M = np.array([[.4124, .3576, .1805], [.2126, .7152, .0722], [.0193, .1192, .9505]])
    xyz = c @ M.T / np.array([.95047, 1, 1.08883])
    f = np.where(xyz > .008856, np.cbrt(xyz), 7.787 * xyz + 16 / 116)
    L = 116 * f[..., 1] - 16
    a = 500 * (f[..., 0] - f[..., 1]); b = 200 * (f[..., 1] - f[..., 2])
    return L, a, b

out = []
for slug, title, artist, img in items:
    im = Image.open(os.path.join(ROOT, img)).convert("RGB")
    W = 300; H = round(im.height * W / im.width)
    arr = np.asarray(im.resize((W, H), Image.LANCZOS), dtype=float)
    L, a, b = to_lab(arr)
    r, step, cands = 3, 4, []
    for y in range(r + 6, H - r - 6, step):
        for x in range(r + 6, W - r - 6, step):
            win = L[y - r:y + r + 1, x - r:x + r + 1]
            sd = win.std()
            if sd < 2.2:
                aw, bw = a[y - r:y + r + 1, x - r:x + r + 1].mean(), b[y - r:y + r + 1, x - r:x + r + 1].mean()
                cands.append((sd, x, y, float(win.mean()), float(np.hypot(aw, bw))))
    # spread: greedy over a shuffled-by-lightness order so every value range is represented
    rng = np.random.default_rng(7)
    rng.shuffle(cands)
    cands.sort(key=lambda c: round(c[3] / 6))   # bucket by L*, then take spots across buckets
    buckets = {}
    for c in cands: buckets.setdefault(round(c[3] / 6), []).append(c)
    picked, minD = [], 0.07 * W
    while any(buckets.values()) and len(picked) < 70:
        for k in sorted(buckets):
            while buckets[k]:
                c = buckets[k].pop()
                if all((c[1] - p[1]) ** 2 + (c[2] - p[2]) ** 2 >= minD ** 2 for p in picked):
                    picked.append(c); break
    pts = sorted([[round(c[1] / W * 1000), round(c[2] / H * 1000), round(c[3], 1), round(c[4], 1)] for c in picked], key=lambda p: p[2])
    Ls = [p[2] for p in pts]
    print(f"{slug:24s} {len(pts):3d} spots, L* {min(Ls):.0f}-{max(Ls):.0f}")
    out.append({"id": slug, "title": title, "artist": artist, "img": img, "w": im.width, "h": im.height, "pts": pts})

hdr = ("// Squint station: spots with a known lightness in each painting. Generated by tools/squint.py; edit that, not this.\n"
       "// pts = [x per mille, y per mille, L* (CIELAB), C*], measured on a 300 px copy over a flat 7x7 patch.\n"
       "// Precomputed because reading pixels in the browser fails on file:// pages and on non-CORS images.\n")
body = ",\n".join("  " + json.dumps(p, ensure_ascii=False, separators=(",", ":")) for p in out)
open(os.path.join(ROOT, "data/squint.js"), "w", encoding="utf8").write(hdr + "window.SQUINT = [\n" + body + "\n];\n")
print("wrote data/squint.js")
