// Builds the table inside js/today.js: for each of the 292 days of Today's painting, the one core name that painting
// really holds (as photographed): its nearest-name share >= 2% at dE <= 7, weighted x3 for names with an article and
// by how much more of it this painting has than the average painting (distinctive). Names don't repeat until all
// have been used. Black, white, greys and near-neutrals only when no chromatic name qualifies. Deterministic. Run: node tools/today_table.js        (rewrites the block between the markers)
const fs = require("fs"), path = require("path");
const { lab, lch, de2000 } = require("./colormath.js");
const R = p => path.join(__dirname, "..", p);
const meta = JSON.parse(fs.readFileSync(R("data/daily-paint.json"), "utf8"));
const rows = []; for (let s = 0; s * meta.per < meta.n; s++) rows.push(...JSON.parse(fs.readFileSync(R(`data/daily-paint/${s}.json`), "utf8")));
const SKIP = /\b(ugly|windows|puke|vomit|barf|poop|light light|dark dark)\b/i;
const core = JSON.parse(fs.readFileSync(R("data/core-names.json"), "utf8")).filter(e => !e.compound && !SKIP.test(e.n) && e.rank != null && e.rank < 450).map(e => ({ ...e, lab: lab(e.h) }));
const slug = n => n.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const art = new Set(fs.readdirSync(R("data/articles")).filter(f => f.endsWith(".json")).map(f => f.replace(/\.json$/, "")));
const covAt = maxDe => rows.slice(0, meta.n).map(e => {
  const m = new Map();
  for (const [hex, sh] of e.pool) {
    let best = null, bd = 1e9;
    for (const c of core) { const d = de2000(hex, c.h); if (d < bd) { bd = d; best = c; } }
    if (best && bd <= maxDe) m.set(best.n, (m.get(best.n) || 0) + sh);
  }
  return m;
});
const cov = covAt(7), loose = covAt(11);   // a few muted paintings hold no name at dE 7: widen for those only
const mean = new Map(); for (const m of cov) for (const [n, s] of m) mean.set(n, (mean.get(n) || 0) + s / cov.length);
const hash = s => { let h = 2166136261; for (const ch of s) { h ^= ch.charCodeAt(0); h = Math.imul(h, 16777619); } return h >>> 0; };
// near-neutral: chroma under 10 (cement, ash, taupe), or a black / white / grey word whatever its slight tint
const isNeutral = (n, h) => lch(h)[1] < 10 || /\b(black|white|gr[ae]y|silver|charcoal|dark|gunmetal|slate)\b/i.test(n);
const used = new Set(), out = [];
cov.forEach((m0, i) => {
  let m = m0; if (![...m].some(([, s]) => s >= 0.02)) m = loose[i];
  const candOf = m => [...m].filter(([n, s]) => s >= 0.02).map(([n, s]) => {
    const c = core.find(x => x.n === n), C = lch(c.h)[1];
    return { n, h: c.h, s, neutral: isNeutral(n, c.h), w: Math.sqrt(s) * Math.min(4, s / (mean.get(n) || s)) * (art.has(slug(n)) ? 3 : 1) * (C < 6 ? 0.3 : 1 + C / 25) };
  }).sort((a, b) => b.w - a.w);
  let cand = candOf(m);
  // a muted painting with only neutral names at dE 7 may still hold a chromatic one at the looser dE 11
  if (!cand.some(c => !c.neutral) && m !== loose[i] && candOf(loose[i]).some(c => !c.neutral)) cand = candOf(loose[i]);
  // "Today, X in Y" should name a color you can see: black, white, the greys and near-neutrals only when the
  // painting holds no chromatic name at all (David, 2026-10-08: "in black" was a weak pick)
  if (cand.some(c => !c.neutral)) cand = cand.filter(c => !c.neutral);
  let pool = cand.filter(c => !used.has(c.n)); if (!pool.length) pool = cand;
  pool = pool.slice(0, 4); const tot = pool.reduce((a, c) => a + c.w, 0);
  let r = (hash("today-v1-" + i) / 4294967296) * tot, pick = pool[0];
  for (const c of pool) { if ((r -= c.w) <= 0) { pick = c; break; } }
  if (!pick) { console.log("none", i, rows[i].id, JSON.stringify(rows[i].pool.slice(0,4)), m.size); return; }
  used.add(pick.n); out.push([rows[i].id, pick.n, pick.h, Math.round(pick.s * 1000) / 10]);
});
const file = R("js/today.js"), src = fs.readFileSync(file, "utf8");
const block = "// TABLE-START (generated by tools/today_table.js)\nconst TODAY_TABLE = [\n" + out.map(r => "  " + JSON.stringify(r)).join(",\n") + "\n];\n// TABLE-END";
fs.writeFileSync(file, src.replace(/\/\/ TABLE-START[\s\S]*\/\/ TABLE-END/, block));
console.log(out.length, "days;", new Set(out.map(r => r[1])).size, "distinct colors");
