// Builds data/games/whose.js for the "Whose palette?" station (js/games/oo-whose.js). Run: node tools/whose_build.js
// Source: data/analysis/artists/*.json (tools/analyze.py). A round is five colors from one of a painter's palette
// clusters; the three answers are painters, each shown with a strip of colors from their paintings (the barcode:
// the dominant colors of every painting). Only provably solvable rounds are kept: the five colors must sit clearly
// nearer the right painter's strip than either distractor's (mean nearest ΔE00, by a margin), and the right
// painter's strip never repeats a shown color by name, so it can't be solved by matching identical chips.
// Honest caveat (shown in the station): these are photographs of varnished paintings, so palettes lean brown.
const fs = require("fs"), path = require("path");
const { lab, lch, de2000 } = require("./colormath.js");
const root = path.join(__dirname, "..");
const hexOf = new Map();
for (const [n, h] of JSON.parse(fs.readFileSync(path.join(root, "data/color-names.json"), "utf8"))) if (!hexOf.has(n.toLowerCase())) hexOf.set(n.toLowerCase(), h);
for (const e of JSON.parse(fs.readFileSync(path.join(root, "data/library.json"), "utf8"))) if (!hexOf.has(e.n.toLowerCase())) hexOf.set(e.n.toLowerCase(), e.h);
for (const e of JSON.parse(fs.readFileSync(path.join(root, "data/core-names.json"), "utf8"))) if (!hexOf.has(e.n.toLowerCase())) hexOf.set(e.n.toLowerCase(), e.h);
const hx = n => hexOf.get(String(n).toLowerCase());

const MIN_N = 12, STRIP = 12, MARGIN = 8, FAR = 10;
const dir = path.join(root, "data/analysis/artists");
const painters = [];
for (const f of fs.readdirSync(dir).filter(f => f.endsWith(".json")).sort()) {
  const a = JSON.parse(fs.readFileSync(path.join(dir, f), "utf8"));
  if (a.n < MIN_N || !a.clusters || !a.clusters.length) continue;
  // the strip: every painting's dominant colors, de-duplicated (ΔE < 4), weighted by how often they appear
  const count = new Map();
  a.barcode.forEach(b => b[2].forEach(n => { if (hx(n)) count.set(n, (count.get(n) || 0) + 1); }));
  const strip = [];
  [...count].sort((x, y) => y[1] - x[1]).forEach(([n]) => { const h = hx(n); if (strip.length < STRIP * 2 && strip.every(s => de2000(s.h, h) >= 4)) strip.push({ n, h }); });
  painters.push({ s: a.slug, name: a.name, n: a.n, country: a.country || "", find: (a.findings || [])[0] || "", strip, clusters: a.clusters });
}
// mean, over the shown colors, of the nearest strip color (ΔE00)
const dist = (shown, strip) => shown.reduce((s, h) => s + Math.min(...strip.map(x => de2000(h, x.h))), 0) / shown.length;
const rounds = [], idx = new Map(painters.map((p, i) => [p.s, i]));
let rejected = 0;
for (const p of painters) {
  p.clusters.forEach((c, ci) => {
    if (c.size < 4 || c.pct < 20) return;
    const shown = c.colors.map(hx).filter(Boolean);
    if (shown.length < 4) return;
    const names = new Set(c.colors.map(x => x.toLowerCase()));
    const own = p.strip.filter(x => !names.has(x.n.toLowerCase())).slice(0, STRIP);
    if (own.length < 6) return;
    const dOwn = dist(shown, own), ok = [];
    for (const q of painters) {
      if (q.s === p.s) continue;
      const dq = dist(shown, q.strip.slice(0, STRIP));
      if (dq >= dOwn + MARGIN && dq >= FAR) ok.push([q.s, +dq.toFixed(1)]);
    }
    if (ok.length < 2) { rejected++; return; }
    // keep distractors spread across the eligible range (not only the easiest)
    ok.sort((x, y) => x[1] - y[1]);
    const K = 8, pick = ok.length <= K ? ok : Array.from({ length: K }, (_, i) => ok[Math.floor(i * (ok.length - 1) / (K - 1))]);
    // compact: painters by index; the right painter's strip as indices into its own strip
    rounds.push([idx.get(p.s), shown.map(h => h.slice(1)).join(""), own.map(x => x.h.slice(1)).join(""), pick.map(x => idx.get(x[0]))]);
  });
}
const out = {
  painters: painters.map(p => [p.s, p.name, p.n, p.country, p.find, p.strip.slice(0, STRIP).map(x => x.h.slice(1)).join("")]),
  rounds,
};
fs.mkdirSync(path.join(root, "data/games"), { recursive: true });
fs.writeFileSync(path.join(root, "data/games/whose.js"),
  "// Whose palette? rounds. Generated by tools/whose_build.js from data/analysis/artists; edit that script, not this file.\n" +
  "// painters: [slug, name, paintings, country, one finding, strip (hex digits, 6 per color)].\n" +
  "// rounds: [painter index, shown (hex digits), the painter's strip without the shown names (hex digits), distractor indices].\n" +
  "window.OO_WHOSE = " + JSON.stringify(out) + ";\n");
console.log(`whose: ${rounds.length} solvable rounds from ${painters.length} painters (${rejected} clusters rejected as unsolvable)`);
